functionsDirectory = "/Users/user/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/user/MeteoESP"
publishOrigin = "config"
functions = "/Users/user/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/relay/on"
to = "/.netlify/functions/relayOn"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/relay/off"
to = "/.netlify/functions/relayOff"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/state"
to = "/.netlify/functions/getState"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]